runtime: python312
automatic_scaling:
  target_cpu_utilization: 0.92
  max_concurrent_requests: 70
  target_throughput_utilization: 0.70
  max_instances: 5
entrypoint: gunicorn -b :$PORT index:server
